name: Cypress Tests
on: 
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * 0"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:tag1

      - name: Upload screenshots
        uses: actions/upload-artifact@v4.0.0
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
