name: Cypress Tests
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:tag1

      - name: Upload screenshots
        uses: actions/upload-artifact@v4.6.0
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots